my_app/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path("login/", views.LoginView, name="login"),
    path("register/", views.RegisterView, name="register"),
    path("dashboard/", views.DashboardView, name="dashboard"),
    path("logout/", views.LogoutView, name="logout"),
    path("data/", views.DataView, name="all_data"),
    path("data/<str:pk>", views.DataView, name="data"),
    path("coin/<str:pk>", views.CoinView, name="coin"),
    path("",views.BaseView, name="base"),
    re_path(r'^.*$', views.handler404, name="404"),
]

my_project/my_app/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path("login/", views.LoginView, name="login"),
    path("register/", views.RegisterView, name="register"),
    path("dashboard/", views.DashboardView, name="dashboard"),
    path("logout/", views.LogoutView, name="logout"),
    path("data/", views.DataView, name="all_data"),
    path("data/<str:pk>", views.DataView, name="data"),
    path("coin/<str:pk>", views.CoinView, name="coin"),
    path("",views.BaseView, name="base"),
    re_path(r'^.*$', views.handler404, name="404"),
]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("my_app.urls")),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("my_app.urls")),
]

my_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from datetime import datetime
import json

# Create your models here.
class CustomUser(AbstractUser):
    portfolio_graph_default = {"date": [], "value": []}
    coins = models.ManyToManyField(to="Coin", through="Holding")
    money = models.DecimalField(max_digits=100, decimal_places=2, validators=[MinValueValidator(50)] )
    portfolio_graph = models.TextField(default=json.dumps(portfolio_graph_default))
    portfolio_value = models.DecimalField(max_digits=100, decimal_places=2)

class Holding(models.Model):
    coin = models.ForeignKey("Coin", on_delete=models.CASCADE)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1)])
    price_bought_at = models.DecimalField(decimal_places=10, max_digits=20)

class Coin(models.Model):
    graph_default = {"date": [], "value": []}
    symbol = models.CharField(max_length=3)
    name = models.CharField(max_length=100)
    image_url = models.CharField(max_length=256)
    price = models.DecimalField(max_digits=15,decimal_places=10)
    market_cap = models.DecimalField(max_digits=20,decimal_places=2)
    volume = models.IntegerField()
    high_24h = models.DecimalField(max_digits=20,decimal_places=2)
    low_24h = models.DecimalField(max_digits=20,decimal_places=2)
    change_24h = models.DecimalField(max_digits=20,decimal_places=2)
    percent_change_24h = models.DecimalField(max_digits=20,decimal_places=2)
    graph = models.TextField(default=json.dumps(graph_default))

my_project/my_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from datetime import datetime
import json

# Create your models here.
class CustomUser(AbstractUser):
    portfolio_graph_default = {"date": [], "value": []}
    coins = models.ManyToManyField(to="Coin", through="Holding")
    money = models.DecimalField(max_digits=100, decimal_places=2, validators=[MinValueValidator(50)] )
    portfolio_graph = models.TextField(default=json.dumps(portfolio_graph_default))
    portfolio_value = models.DecimalField(max_digits=100, decimal_places=2)

class Holding(models.Model):
    coin = models.ForeignKey("Coin", on_delete=models.CASCADE)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1)])
    price_bought_at = models.DecimalField(decimal_places=10, max_digits=20)

class Coin(models.Model):
    graph_default = {"date": [], "value": []}
    symbol = models.CharField(max_length=3)
    name = models.CharField(max_length=100)
    image_url = models.CharField(max_length=256)
    price = models.DecimalField(max_digits=15,decimal_places=10)
    market_cap = models.DecimalField(max_digits=20,decimal_places=2)
    volume = models.IntegerField()
    high_24h = models.DecimalField(max_digits=20,decimal_places=2)
    low_24h = models.DecimalField(max_digits=20,decimal_places=2)
    change_24h = models.DecimalField(max_digits=20,decimal_places=2)
    percent_change_24h = models.DecimalField(max_digits=20,decimal_places=2)
    graph = models.TextField(default=json.dumps(graph_default))

my_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, Holding

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username','password1','password2','money']

class OrderForm(forms.ModelForm):
    class Meta():
        model = Holding
        fields = ['quantity']

my_project/my_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, Holding

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username','password1','password2','money']

class OrderForm(forms.ModelForm):
    class Meta():
        model = Holding
        fields = ['quantity']






my_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, OrderForm
from .models import CustomUser, Coin, Holding
from django.http import JsonResponse
from django.db.models import Q
from django.contrib import messages
from decimal import Decimal
import json
from datetime import datetime

# Create your views here.
def handler404(request):
    if request.user.is_authenticated:
        return render(request, 'myapp/authenticated404.html', status=404)

    return render(request, 'myapp/unauthenticated404.html', status=404)

def LoginView(request):
    if request.method == "GET":
        return render(request, "myapp/login.html", {"form":AuthenticationForm()})
    
    else:
        form = AuthenticationForm(data=request.POST)   

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect("dashboard")
            
        return render(request, "myapp/login.html", {"form":form})

def RegisterView(request):
    if request.method == "GET":
        return render(request, "myapp/register.html",{"form":CustomUserCreationForm()})
    
    else:
        form = CustomUserCreationForm(data=request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.portfolio_value = user.money
            user.portfolio_graph = json.dumps({"date": [str(datetime.now())], "value": [float(user.money)]})
            user.save()
            login(request,user)
            return redirect('dashboard')

    return render(request, "myapp/register.html", {"form":form})

def DashboardView(request):
    if not request.user.is_authenticated:
        messages.error(request,"You do not have permission to access this page.")
        return redirect('login')
    coins = Coin.objects.all()
    holdings = Holding.objects.filter(owner=request.user)
        
    # we want a pie chart where each section represents one coin.
    # However, one user can have many holdings of the same coin.
    # To do this, we follow the below steps.
    # repeat steps 1-4 for each coin owned by the user:
    # 1. initialize variable coin_cost, coin_value, coin_quantity = 0
    # 2. For each holding of this coin, add its cost to coin_cost,
    # add its value to coin_value, and add holding.quantity to coin_quantity
    # 3. let coin_revenue_percent=(coin_value - coin_cost)/coin_cost
    # 4. push coin_quantity and coin_revenue_percent into an array

    # let our final data array be represented by piechart_data
    piechart_data = {"data":[]}

    # Before we do this, need to find the list of coins owned by user
    coins = set({})
    for holding in holdings:
        coins.add(holding.coin)
    
    # now, we can execute the steps listed above
    for coin in coins:
        coin_holdings = Holding.objects.filter(coin=coin)

        # 1. initialize variable coin_cost, coin_value, coin_quantity = 0
        coin_cost = 0
        coin_value = 0
        coin_quantity = 0

        # 2. For each holding of this coin, add its cost to coin_cost,
        # add its value to coin_value, and add holding.quantity to coin_quantity
        for holding in coin_holdings:
            coin_cost += (holding.quantity * holding.price_bought_at)
            coin_value += (holding.quantity * coin.price)
            coin_quantity += holding.quantity

        # 3. let coin_revenue_percent=(coin_value - coin_cost)/coin_cost
        coin_revenue_percent = round(100*(coin_value - coin_cost)/coin_cost,2)

        # 4. push coin, coin_quantity and coin_revenue_percent into an array
        piechart_data['data'].append({"coin_name":coin.name,"coin_value":float(coin_value), "coin_quantity":float(coin_quantity), "coin_revenue_percent":float(coin_revenue_percent)})
    
    # add user's cash to piechart_data 
    piechart_data['data'].append({"coin_name":"Cash","coin_value":float(request.user.money), "coin_quantity":float(request.user.money), "coin_revenue_percent":float(0)})

    # convert dictionary into json
    piechart_data_json = json.dumps(piechart_data)
    

    if request.method == "GET":
        return render(request, "myapp/dashboard.html", {"coins":coins, "holdings":holdings, "piechart_data":piechart_data_json, "crypto_value":request.user.portfolio_value - request.user.money})

def LogoutView(request):
    if request.method == "POST":
        logout(request)
        messages.success(request,"Successfully logged out.")
        return redirect("login")

def DataView(request,pk=""):
    if request.method == "GET":
        if (pk is not None):
            data = list(Coin.objects.filter(Q(symbol__contains = pk) | Q(name__contains = pk)).values())
        else:
            data = Coin.objects.all()
        return JsonResponse({"data":data})

def CoinView(request,pk):
    if not request.user.is_authenticated:
        messages.error(request,"You do not have permission to access this page.")
        return redirect('login')
    # coin represents current coin
    order_coin = Coin.objects.get(symbol=pk)

    # find any holdings of this coin the current user already has
    holdings = Holding.objects.filter(owner=request.user,coin=order_coin)
    number_owned = 0

    # find total amount of this coin owned by the user
    for holding in holdings:
        number_owned += holding.quantity

    if request.method == "GET":
        return render(request,"myapp/coin.html",{"coin":Coin.objects.get(symbol=pk),"form":OrderForm(), "number_owned":number_owned})
    
    if request.method == "POST":
        form = OrderForm(data=request.POST)
        if form.is_valid():
            order_coin = Coin.objects.get(symbol=pk)
            order_price = order_coin.price
            order_quantity = Decimal(request.POST.get("quantity"))
            order_type = request.POST.get("order-type")

            # case where order type is "buy"
            if order_type == "buy":
                cost = order_price * order_quantity
                if cost <= request.user.money:
                    request.user.money -= cost
                    request.user.portfolio_value += cost
                    request.user.save()

                    # create new holding to represent this purchase
                    Holding.objects.create(coin=order_coin,owner=request.user,quantity=order_quantity, price_bought_at=order_price)
                    messages.success(request, f"Successfully purchased {order_quantity} {pk} for ${round(cost,2)}")
                    return redirect("dashboard")
                else:
                    messages.error(request,"Order unsuccesssful (insufficient funds).")
                    return render(request,"myapp/coin.html",{"coin":Coin.objects.get(symbol=pk),"form":form,"number_owned":number_owned})
                
            if order_type == "sell":
                # case where order type is "sell"
                # check if the user has at least quantity of this coin
                # by iterating through each of their holdings of this coin
                # let remainder denote what is "left over" after
                # subtracting the holding quantity from the order quantity
                total_quantity = 0

                for holding in holdings:
                    total_quantity += holding.quantity
                
                # if the user has less than quantity of this coin,
                # reject the order
                if order_quantity > total_quantity:
                    messages.error(request,"Order unsuccesssful (you don't own enough of this coin).")
                    return render(request,"myapp/coin.html",{"coin":Coin.objects.get(symbol=pk),"form":form,"number_owned":number_owned})
                
                # otherwise, the order is valid.
                # sell off each of the user's holdings until
                # we reach quantity
                order_quantity_copy = order_quantity
                holdings_copy = holdings

                for holding in holdings_copy:
                    remainder = max(0,holding.quantity - order_quantity_copy)
                    order_quantity_copy = max(order_quantity_copy - holding.quantity,0)
                    holding.quantity = remainder

                    # if the holding's quantity is now zero, delete it
                    if holding.quantity == 0:
                        holding.delete()
                    
                    # else, save it
                    if holding.quantity > 0:
                        holding.save()

                    # if quantity is zero, we can stop
                    if order_quantity_copy == 0:
                        break

                profit = Decimal(order_quantity) * Decimal(order_price)
                request.user.money += profit
                request.user.portfolio_value -= profit
                request.user.save()
                messages.success(request,f"Successfully sold {order_quantity} {order_coin.name} for {order_quantity * order_price}.")
                return redirect("dashboard")
            
def BaseView(request):
    if request.user.is_authenticated:
        return redirect("dashboard")

    return redirect("login")

my_project/my_app/templates/myapp/authenticated404.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@600&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.umd.min.js"></script>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js" charset="utf-8"></script>
    <script src="https://kit.fontawesome.com/2226da885e.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'myapp/dashboard.css' %}">
</head>
<body class="dashboard-body">
    {% for message in messages %}
    <div class="alert alert-success message" role="alert" style="margin-bottom:0px;">
    {{ message }}
    </div>
    {% endfor %}
    <nav class="navbar">
        <div class="left-links">
            <a href="{% url 'dashboard' %}" class="navbar-link crypto100-link" style="font-size:25px;">Crypto100</a>
            <a href="https://www.coingecko.com/" class="navbar-link dashboard-link" >Powered by CoinGecko</a>
            <a href="{% url 'dashboard' %}" class="navbar-link dashboard-link" >Dashboard</a>
            <a href="{% url 'dashboard' %}" class="navbar-link about-link">About</a>
        </div>
        <div class="right-links">
            <a class="navbar-link">Currently logged in as {{ user }}</a>
            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <input type="submit" value="Logout" 
                       class="btn btn-primary">
            </form>
        </div>
    </nav>
    <div style="width:100%; background-color: white; z-index:20; padding:30px;">
        <h1>Page Not Found</h1>
        <p>Sorry, the page you are looking for might be unavailable or does not exist.</p>
    </div>
</body>
</html>

my_project/my_app/templates/myapp/coin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href= "{{coin.image_url}}" type="image/x-icon">
    <title>Trade {{ coin.name }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@600&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/2226da885e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'myapp/dashboard.css' %}">
</head>
<body class="coin-body">

    <!-- bootstrap stuff -->
    <nav class="navbar">
      <div class="left-links">
          <a href="{% url 'dashboard' %}" class="navbar-link crypto100-link" style="font-size:25px;">Crypto100</a>
          <a href="{% url 'dashboard' %}" class="navbar-link dashboard-link" >Dashboard</a>
          <a href="{% url 'dashboard' %}" class="navbar-link about-link">About</a>
      </div>
      <div class="right-links">
          <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <input type="submit" value="Logout" 
                     class="btn btn-primary">
          </form>
      </div>
  </nav>
    <div class="coinpage">
        <div class="coin-info coinpage-child">
            <h1>{{ coin.name }}</h1>
            <h2>{{ coin.symbol }} </h2>
            <h3><span class="price">{{ coin.price }}</span><span class="currency">AUD</span></h3>
            <br>
            <p class="you-own">You own {{ number_owned }} {{ coin.symbol }}.</p>
            <p>Market cap: {{ coin.market_cap }}</p>
            <p>Volume: {{ coin.volume }}</p>
            <p>24-hour high: {{ coin.high_24h }}</p>
            <p>24-hour low: {{ coin.low_24h }}</p>
            <p>24-hour change: {{ coin.change_24h }}</p>
            <p>24-hour change (%): {{ coin.percent_change_24h }}</p>          
        </div>
        <div class="order coinpage-child">
          <p>You have {{ user.money }}AUD.</p>
          {% load crispy_forms_tags %}
            <form class="order-form" method="post" action="{% url 'coin' pk=coin.symbol  %}">
              {% csrf_token %}
              <div class="buysell-button">
                <div class="buy" onclick="trigger(buy=true)" style="opacity:1; font-weight:800;">Buy</div>
                <div class="sell" onclick="trigger(buy=false)" style="opacity:0.2;">Sell</div>
              </div>
              <br>
              {{ form|crispy }}
              <input type="hidden" name="price" value="{{coin.price}}">
              <input id="order-type" type="hidden" name="order-type" value="buy">
              <p>{{ coin.symbol }} for <span class="total_price">0.00</span>AUD</p>
              {% for message in messages %}
              <p class="{{ message.tags }}">{{ message }}</p>
              {% endfor %}
              <input type="submit" value="Confirm" class="btn btn-primary">
            </form>
        </div>
        <div class="plot coinpage-child">
          <label class="line-label">Coin value over time</label>
          <div class='linechart-div-coin' id="linechart-div-coin">
              <script>
                  var unparsed_line = '{{ coin.graph | escapejs }}'
                  var parsed_line = JSON.parse(unparsed_line);
  
                  var data = [
                      {
                          x: parsed_line['date'],
                          y: parsed_line['value'],
                          type: 'scatter'
                      }
                  ];
  
                  Plotly.newPlot('linechart-div-coin', data);
              </script>
          </div>
        </div>
    </div>
    <script>
      let order_quantity = document.querySelector(".order-form #id_quantity")
      let price = document.querySelector(".price");
      let total_price = document.querySelector(".total_price");
      order_quantity.addEventListener("input",calculatePrice);

      function calculatePrice()
      {
        total_price.innerHTML = (order_quantity.value * price.innerHTML).toFixed(2);
      }
      
      function trigger(buy)
      {
        const button1 = document.querySelector(".buy");
        const button2 = document.querySelector(".sell");
        const order_type = document.querySelector("#order-type");

        if (buy === true)
        {
          button1.style.opacity = 1;
          button1.style = "font-weight:1000;"
          button2.style.opacity = 0.2;
          order_type.value = "buy";
        }
        else
        {
          button1.style.opacity = 0.2;
          button2.style.opacity = 1;
          button2.style = "font-weight:1000;"
          order_type.value = "sell";
        }
        
      }

      calculatePrice()
    </script>
</body>
</html>

my_project/my_app/templates/myapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'myapp/dashboard.css' %}">
</head>
<body class="login-body register-body">
    <div class="user-div login-div">
        <h1>Login</h1>
        {% for message in messages %}
        <p class="{{ message.tags }}">{{ message }}</p>
        {% endfor %}
        {% load crispy_forms_tags %}
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-primary" value="Login">
        </form>
        <br>
        <a href="{% url 'register' %}" class>Don't have an account? Register.</a>
    </div>
</body>
</html>

my_project/my_app/templates/myapp/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'myapp/dashboard.css' %}">
</head>
<body class="login-body register-body">
    <div class="user-div register-div">
    <h1>Register</h1>
        {% load crispy_forms_tags %}
        <form method="post" action="{% url 'register' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <p style="font-size:13px; color:grey;">How much money you'll start out with</p>
            <input type="submit" class="btn btn-primary" value="Start Trading!">
        </form>
        <br>
        <a href="{% url 'login' %}">Back to login</a>
    </div>
</body>
</html>

my_project/my_app/templates/myapp/unauthenticated404.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page not found</title>
    <link rel="stylesheet" href="{% static 'myapp/dashboard.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body class="login-body register-body" style="margin:0px;">
    <div style="background-color:white; width:100%; padding:20px; margin:0px;">
        <h1>Page Not Found</h1>
        <p>Sorry, the page you are looking for might be unavailable or does not exist.</p>
        <a href="{% url 'login' %}" style="display:block; text-decoration:none;">Back to login</a>
        <a href="{% url 'register' %}" style="text-decoration:none;">Register</a>
    </div>
</body>
</html>